"""Load and validate the offline-prepared GenPlaylist-v4 DatasetDict."""

from __future__ import annotations

import json
from pathlib import Path

from shared.artifacts import sha256_file
from shared.protocol import FROZEN_NEXT_SONG_PROTOCOL
from shared.schema import SCHEMA_VERSION, TOKEN_LAYOUT


PREPARED_DATA_VERSION = "genplaylist-v4-configurable-cues-20item-joint-15to5"
EXPECTED_SPLIT_COUNTS = {"train": 57331, "test": 941}
PREPARATION_CODE_FILES = (
    "scripts/prepare_wp_c_data.py",
    "src/00_data_schema/schema.py",
    "src/03_backbone_recommender/dataset.py",
    "src/03_backbone_recommender/genplaylist_tokenizer.py",
    "src/03_backbone_recommender/prepared_data.py",
    "src/shared/artifacts.py",
    "src/shared/protocol.py",
    "src/shared/schema.py",
)


def expected_split_counts(dataset=None) -> dict[str, int]:
    """Return dataset-specific frozen counts, with MPD as the legacy default."""
    if dataset is None:
        return dict(EXPECTED_SPLIT_COUNTS)
    configured = dataset.dataset_card.get("wp_c_split_counts")
    if configured is None:
        return dict(EXPECTED_SPLIT_COUNTS)
    if not isinstance(configured, dict) or set(configured) != {"train", "test"}:
        raise ValueError(
            "dataset_card.wp_c_split_counts must contain exactly train and test")
    counts = {name: int(value) for name, value in configured.items()}
    if any(value <= 0 for value in counts.values()):
        raise ValueError("WP-C train/test counts must both be positive")
    return counts


def preparation_code_manifest(repo_root: str | Path | None = None) -> dict:
    """Hash the code and config whose behavior defines the offline cache."""
    root = (
        Path(repo_root).expanduser().resolve()
        if repo_root is not None
        else Path(__file__).resolve().parents[2]
    )
    output = {}
    for relative in PREPARATION_CODE_FILES:
        path = root / relative
        if not path.is_file():
            raise FileNotFoundError(path)
        output[relative] = {
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        }
    return output


def validate_preparation_code(manifest: dict) -> None:
    """Reject a cache generated by different preparation semantics."""
    frozen = manifest.get("preparation_code")
    current = preparation_code_manifest()
    if not isinstance(frozen, dict):
        raise ValueError("Prepared manifest has no preparation_code fingerprints")
    for relative, current_entry in current.items():
        frozen_entry = frozen.get(relative)
        if frozen_entry is None or frozen_entry.get("sha256") != current_entry["sha256"]:
            raise ValueError(
                f"Prepared code hash mismatch for {relative}: "
                f"prepared={None if frozen_entry is None else frozen_entry.get('sha256')} "
                f"current={current_entry['sha256']}")


def configured_source_paths(config, dataset) -> dict[str, Path]:
    """Resolve every source file whose bytes define a prepared dataset."""
    data_root = Path(dataset.dir)
    repo_root = Path(__file__).resolve().parents[2]
    cue_root = repo_root / "src" / "02_creative_cues" / "outputs" / "production" / "latest"

    def configured(name: str, default: Path) -> Path:
        value = config.get(name, None)
        return Path(value).expanduser().resolve() if value else default.resolve()

    return {
        "catalog_metadata": (data_root / "catalog_metadata.json").resolve(),
        "train_split": (data_root / "splits" / "train.txt").resolve(),
        "val_split": (data_root / "splits" / "val.txt").resolve(),
        "test_split": (data_root / "splits" / "test.txt").resolve(),
        "catalog_embeddings": configured(
            "catalog_embeddings_path", data_root / "catalog_item_embeddings.npy"),
        "item_id_to_row": configured(
            "item_id_to_row_path", data_root / "item_id_to_row.json"),
        "semantic_tokens": configured(
            "semantic_tokens_path", data_root / "semantic_tokens.json"),
        "rvq_codebook": configured(
            "codebook_weights_path", data_root / "rvq_codebook_weights.npy"),
        "item2cues": configured("item2cues_path", cue_root / "item2cues.json"),
        "cue_vocab": configured("cue_vocab_path", cue_root / "cue_vocab.json"),
        "cue_manifest": configured(
            "cue_manifest_path", cue_root / "cue_manifest.json"),
    }


def source_manifest(paths: dict[str, Path]) -> dict:
    output = {}
    for name, path in paths.items():
        if not path.is_file():
            raise FileNotFoundError(path)
        output[name] = {
            "path": str(path),
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        }
    return output


def validate_prepared_manifest(manifest: dict, config, tokenizer, dataset=None) -> None:
    """Validate protocol/layout/count metadata before loading Arrow files."""
    FROZEN_NEXT_SONG_PROTOCOL.validate_config(config)
    if manifest.get("prepared_data_version") != PREPARED_DATA_VERSION:
        raise ValueError(
            f"Prepared data version mismatch: {manifest.get('prepared_data_version')!r}")
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ValueError(
            f"Prepared schema mismatch: {manifest.get('schema_version')!r}")
    expected_counts = expected_split_counts(dataset)
    if manifest.get("split_counts") != expected_counts:
        raise ValueError(
            f"Prepared split counts drifted: {manifest.get('split_counts')}")
    expected_layout = {
        "tokens_per_item": tokenizer.tokens_per_item,
        "runtime_vocab_size": TOKEN_LAYOUT.runtime_vocab_size,
        "model_length": FROZEN_NEXT_SONG_PROTOCOL.model_token_length(
            tokenizer.tokens_per_item),
    }
    if manifest.get("token_layout") != expected_layout:
        raise ValueError(
            f"Prepared token layout mismatch: {manifest.get('token_layout')}")
    configured_condition = str(config.get("history_condition", "full"))
    prepared_condition = prepared_history_condition(manifest)
    if prepared_condition != configured_condition:
        raise ValueError(
            f"Prepared history condition mismatch: prepared={prepared_condition!r} "
            f"configured={configured_condition!r}")


def prepared_history_condition(manifest: dict) -> str:
    """Caches built before the conditioning ablation are all ``full``."""
    return str(manifest.get("history_condition", {}).get("condition", "full"))


def load_prepared_tokenized_dataset(root: str | Path, config, dataset, tokenizer):
    """Verify source hashes, load the tokenized DatasetDict, and set torch format."""
    from datasets import load_from_disk

    root = Path(root).expanduser().resolve()
    manifest_path = root / "prepared_manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"Prepared dataset manifest not found: {manifest_path}. "
            "Run scripts/prepare_wp_c_data.py first.")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    validate_prepared_manifest(manifest, config, tokenizer, dataset)
    validate_preparation_code(manifest)

    current_sources = source_manifest(configured_source_paths(config, dataset))
    frozen_sources = manifest.get("source_artifacts", {})
    for name, current in current_sources.items():
        frozen = frozen_sources.get(name)
        if frozen is None or frozen.get("sha256") != current["sha256"]:
            raise ValueError(
                f"Prepared source hash mismatch for {name}: "
                f"prepared={None if frozen is None else frozen.get('sha256')} "
                f"current={current['sha256']}")

    tokenized = load_from_disk(str(root / "tokenized_dataset"))
    actual_counts = {split: len(tokenized[split]) for split in tokenized}
    expected_counts = expected_split_counts(dataset)
    if actual_counts != expected_counts:
        raise ValueError(f"Prepared Arrow split counts drifted: {actual_counts}")
    for split in tokenized:
        tokenized[split].set_format(type="torch")
    return tokenized, manifest
